### PR TITLE
Add login & form redirect

### PR DESCRIPTION
**Pull request by sxmichaels**
This PR adds two new features:
* If the user is not logged in, access to any page except `/login` results in a redirect to `/login`
* If the user has not filled out the form, access to any page except `/login` will redirect them to a form whose URL is defined in `.env` as `FORM_URL="https://YOUR_FORM_URL_HERE.com"`

Also, please excuse the excess of commits — I branched off of my non-main branch when I created this which resulted in overlap with my earlier PR.

### CODE REVIEW

**Comment by elfran** [comment]
Hey Spencer, I'm worried that this will introduce a barrier to testing at this stage. Given that login is currently non-functional it seems we're going to have to undo this change to test views when developing. Maybe we should wait on merging in this feature?

**Comment by g-rocket** [comment]
Interacting with the site at all seems to error with `undefined method 'has_completed_form' for #<User:0x00007fec80003a60>`...

**Comment by sxmichaels** [comment]
@elfran Login is currently functional; what gives you an impression otherwise? Furthermore, unit tests should mock every component except the one they are specifically testing, so view test should not rely on the actual login code and should instead mock `@current_user`.

@g-rocket You will need to migrate the database, as the models have updated.

**Comment by elfran** [comment]
@sxmichaels I may just not be setting up my local host properly, but it appears that google sign-in isn't functional yet, when using the link in the application view I'm redirected to an error page (something about the request being incorrectly formatted). Of course for the testing suite  we will mock out the login process, but for manual testing during development (for example if I want to open a view to see that it looks how I expect) I thought it might be a hassle to have to undo your changes in order to get inside different parts of the site.

**Comment by sxmichaels** [comment]
@elfran Oh, I see what you mean. The way the process works is that our login page redirects you to a page hosted by Google that, when you log in, provides its response to our server via the endpoint `/auth/:provider/callback`, where the server to which it response is set in the Google Apps console. There is no way to get it to callback to your local computer; that's just how the service works. I think it is possible to manually create a session but doing so is probably rather annoying. I can look into it later.

For now, I just commented out [the line that enables the feature](https://github.com/hmc-room-draw/room-draw/pull/49/files#diff-55c5b7aecfb519d0e4880eaf2788eb6eR6); this way we can still merge the code now.

**Pull request merged**
